default:
  plugins:
#   - ./src/fdk-starter-plugin
  themes:
#   - ./src/fdk-starter-theme
  ftp:
#     user:
#     password: # optional (will be prompted if not set)
#     scheme: "ftps" # optional (default "ftp")
#     host:
#     port: "3308" # optional (for exotic configs)
#     path: # wordpress root folder path in the server
#     commands: # optional list of lftp commands to run before uploading
#     - set ftp:ssl-allow no
#     - set mirror:parallel-transfer-count 3

# alternative configurations for other environments or resource sets, for example
# staging:
#   extend: default # inherit 'default' project's options
#   plugins:
#   themes:
#   ftp:
