require 'chef_compat/monkeypatches/chef'
require 'chef_compat/monkeypatches/chef/log'
require 'chef_compat/monkeypatches/chef/recipe'
require 'chef_compat/monkeypatches/chef/resource'
require 'chef_compat/monkeypatches/chef/provider'
require 'chef_compat/monkeypatches/chef/resource/lwrp_base'
require 'chef_compat/monkeypatches/chef/exceptions'
require 'chef_compat/monkeypatches/chef/run_context'
